// Regenerates packages/chain/src/vault/blueprint.generated.ts from contracts/plutus.json
// (run after `aiken build`):  node contracts/scripts/gen-ts.mjs
// The chain package embeds the blueprint (no runtime file reads); a vitest test fails if the
// embedded copy drifts from contracts/plutus.json.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const bp = JSON.parse(readFileSync(resolve(here, "../plutus.json"), "utf8"));
const spend = bp.validators.find((v) => v.title === "session_vault.session_vault.spend");
if (!spend) throw new Error("session_vault.session_vault.spend not found in plutus.json");
const out = {
  preamble: bp.preamble,
  title: spend.title,
  hash: spend.hash,
  compiledCode: spend.compiledCode,
  parameters: spend.parameters,
  redeemer: spend.redeemer,
  datum: spend.datum,
  definitions: bp.definitions,
};
const target = resolve(here, "../../packages/chain/src/vault/blueprint.generated.ts");
writeFileSync(
  target,
  `// GENERATED by contracts/scripts/gen-ts.mjs from contracts/plutus.json — do not edit by hand.\n` +
    `export const VAULT_BLUEPRINT = ${JSON.stringify(out, null, 2)} as const;\n`,
);
console.log(`wrote ${target} (hash ${spend.hash}, ${spend.compiledCode.length / 2} bytes)`);
